server:
  port: 8201
feign:
  hystrix:
    enabled: true
integrations:
  alpha-vantage:
    host: https://www.alphavantage.co
    api-key: ${ALPHA_VANTAGE_API_KEY}
firebase:
  config-uri: firebase.json
  database-url: ${FIREBASE_DATABASE_URL}
